"""Task 1: embed_repertoire — turn a TCR repertoire dataframe into
TCR embeddings, in one of two flavors (`embedding_type`):

  "pretrained": the raw 480-dim CLS embedding straight out of the
      masked-language-model-pretrained TCRmeta base encoder. This
      encoder was trained on the local sequence-recovery objective
      (predicting masked residues from context), so its embedding
      specializes on LOCAL structure — motif/sub-sequence-level
      similarity between TCRs.

  "final" (default): 480-dim base embedding -> ensemble of 7
      fine-tuned ResMLP projection heads -> GPA-rotation
      alignment across ensemble members -> mean fusion -> L2-normalized
      64-dim antigen-aware embedding. The fine-tuning
      objective pulls together TCRs recognizing the same antigen
      regardless of local sequence differences, so this embedding
      specializes on OVERALL/global structure — antigen-specificity-
      level similarity.

Note: embedding_type is a choice exposed only on embed_repertoire()
itself. compute_rds, plot_umap, energy_shift, and build_reference always
embed internally with embedding_type="final" — the "pretrained" option
is for users who want the raw local-structure embedding directly (e.g.
for their own downstream analysis), not for TCRmeta's own repertoire-
level statistics, which are all defined/validated against the 64-dim
antigen-aware "final" embedding space.
"""
from __future__ import annotations

import pickle
from typing import Dict, Hashable, List, Optional, Tuple, Union

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader

from ._dataset import DEFAULT_MAX_LEN, TCRDatasetFixedLen, fixedlen_collate
from ._model import SiameseOnEmb_ResMLP, TCRMaskedModel, load_state_dict_flexible
from ._tokenizer import build_token2idx
from ._utils import aggregate_duplicate_clones, resolve_device, validate_repertoire_columns
from ._weights import (
    resolve_base_checkpoint,
    resolve_projection_heads,
    resolve_rotations,
    resolve_vgene_table,
)

CloneKey = Tuple[str, str]

# Module-level cache so repeated calls to embed_repertoire (or internal
# use by compute_rds/plot_umap/energy_shift/build_reference) don't reload
# the ~7 checkpoints from disk every time.
_MODEL_CACHE: Dict[str, dict] = {}
_VGENE_TABLE_CACHE: Optional[pd.DataFrame] = None


def _load_vgene_table() -> pd.DataFrame:
    global _VGENE_TABLE_CACHE
    if _VGENE_TABLE_CACHE is None:
        vg = pd.read_csv(resolve_vgene_table())
        vg["v_gene"] = vg["v_gene"].astype(str).str.strip()
        _VGENE_TABLE_CACHE = vg
    return _VGENE_TABLE_CACHE


def _load_models(device: torch.device) -> dict:
    key = str(device)
    if key in _MODEL_CACHE:
        return _MODEL_CACHE[key]

    token2idx = build_token2idx()

    base_model = TCRMaskedModel()
    base_ckpt = torch.load(resolve_base_checkpoint(), map_location=device)
    load_state_dict_flexible(base_model, base_ckpt)
    base_model.to(device).eval()

    proj_models: List[SiameseOnEmb_ResMLP] = []
    for proj_path in resolve_projection_heads():
        m = SiameseOnEmb_ResMLP(in_dim=480, proj_dim=64, hidden=768, dropout=0.3, depth=3).to(device)
        ck = torch.load(proj_path, map_location=device, weights_only=False)
        load_state_dict_flexible(m, ck)
        m.eval()
        proj_models.append(m)

    with open(resolve_rotations(), "rb") as f:
        rotations = pickle.load(f)

    bundle = {
        "token2idx": token2idx,
        "base_model": base_model,
        "proj_models": proj_models,
        "rotations": rotations,
    }
    _MODEL_CACHE[key] = bundle
    return bundle


@torch.no_grad()
def _build_base_embeddings(
    df_unique: pd.DataFrame,
    base_model: TCRMaskedModel,
    token2idx: Dict[str, int],
    device: torch.device,
    batch_size: int,
    max_len: int,
    num_workers: int,
    use_amp: bool = False,
) -> np.ndarray:
    ds = TCRDatasetFixedLen(df_unique, token2idx, max_len=max_len)
    dl = DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=(device.type == "cuda"),
        collate_fn=fixedlen_collate,
    )
    pad_id = token2idx["[PAD]"]
    base_model.eval().to(device)
    all_embeds = []
    # use_amp defaults to False: fp16 autocast is faster on GPU but introduces
    # ~1e-3-scale numerical drift relative to the original fp32 pipeline.
    # Only enable it if you don't need bit-for-bit-ish reproducibility with
    # embeddings/scores generated by the original (pre-packaging) scripts.
    autocast_enabled = use_amp and device.type == "cuda"
    for _keys, input_ids in dl:
        input_ids = input_ids.to(device, non_blocking=True)
        attention_mask = (input_ids != pad_id).long()
        with torch.autocast(device_type="cuda", enabled=autocast_enabled):
            _, embedding = base_model(input_ids, attention_mask=attention_mask, return_embedding=True)
        cls = embedding[:, 0, :].float()
        all_embeds.append(cls.detach().cpu().numpy())
    return np.concatenate(all_embeds, axis=0)


@torch.no_grad()
def _encode_ensemble(
    proj_models: List[SiameseOnEmb_ResMLP],
    X: np.ndarray,
    device: torch.device,
    batch_size: int,
    l2_normalize_each: bool = True,
) -> List[np.ndarray]:
    X_t = torch.from_numpy(np.asarray(X, dtype=np.float32)).to(device, non_blocking=True)
    outputs = []
    for m in proj_models:
        outs = []
        for b in range(0, len(X_t), batch_size):
            xb = X_t[b : b + batch_size]
            z = m.encode(xb)
            if l2_normalize_each:
                z = torch.nn.functional.normalize(z, dim=-1, eps=1e-8)
            outs.append(z.detach().float().cpu().numpy())
        outputs.append(np.concatenate(outs, axis=0))
    return outputs


def _fuse_ensemble(
    Z_full_list: List[np.ndarray],
    rotations: dict,
    use_weighted_fusion: bool = False,
    weight_tau: float = 10.0,
    l2_normalize_final: bool = True,
) -> np.ndarray:
    M = len(Z_full_list)
    R_list = rotations.get("R_list")
    if R_list is None:
        raise ValueError("'R_list' not found in the GPA rotations file.")
    if len(R_list) != M:
        raise ValueError(
            f"R_list length ({len(R_list)}) != number of projection models ({M}). "
            "The rotation matrices must be in the same order the projection "
            "heads were trained/loaded in."
        )
    Z_aligned = [Z @ R for Z, R in zip(Z_full_list, R_list)]

    if not use_weighted_fusion:
        Z_mean = sum(Z_aligned) / float(M)
    else:
        Z_stack = np.stack(Z_aligned, axis=0)
        mean_vec = Z_stack.mean(axis=0)
        mean_vec = mean_vec / (np.linalg.norm(mean_vec, axis=1, keepdims=True) + 1e-8)
        sims = (Z_stack * mean_vec[None, :, :]).sum(-1)
        W = np.exp(weight_tau * sims)
        W = W / (W.sum(axis=0, keepdims=True) + 1e-8)
        Z_mean = (W[..., None] * Z_stack).sum(axis=0)

    if l2_normalize_final:
        Z_mean = Z_mean / (np.linalg.norm(Z_mean, axis=1, keepdims=True) + 1e-8)
    return Z_mean.astype(np.float32, copy=False)


def embed_repertoire(
    df: pd.DataFrame,
    device: str = "auto",
    batch_size: int = 1024,
    max_unique: Optional[int] = None,
    max_len: int = DEFAULT_MAX_LEN,
    num_workers: int = 0,
    use_amp: bool = False,
    save_path: Optional[str] = None,
    embedding_type: str = "final",
) -> Dict[CloneKey, np.ndarray]:
    """Embed a TCR repertoire into TCR embeddings.

    Parameters
    ----------
    df:
        Repertoire dataframe with exactly the columns 'cdr3aa', 'v_gene',
        'count'.
    device:
        "auto" (default, GPU if available), "cpu", "cuda", "cuda:0", etc.
    batch_size:
        Batch size for both the base-encoder forward pass and the
        projection-head ensemble.
    max_unique:
        If set, only embed the first N unique (cdr3aa, v_gene) clones
        (useful for quick smoke tests on huge repertoires).
    use_amp:
        If True, runs the base-encoder forward pass under fp16 autocast
        on CUDA for extra speed. Off by default: it introduces ~1e-3-scale
        numerical drift relative to embeddings generated by the original
        fp32 pipeline, which matters if you're validating against
        previously published/computed results.
    save_path:
        If given, pickle the resulting embedding dict to this path.
    embedding_type:
        "final" (default) or "pretrained". See the module docstring for
        the full explanation; in short, "pretrained" returns the raw
        480-dim base-encoder CLS embedding (specializes on local
        structure), and "final" runs it through the fine-tuned,
        GPA-aligned projection-head ensemble to produce a
        64-dim antigen-aware embedding (specializes on overall/global
        structure). This choice only applies here — compute_rds,
        plot_umap, energy_shift, and build_reference always use
        embedding_type="final" internally regardless of any
        embedding_type passed to them.

    Returns
    -------
    dict mapping (cdr3aa, v_gene) -> np.ndarray, float32. Shape is (480,)
    for embedding_type="pretrained" or (64,) for embedding_type="final".
    """
    if embedding_type not in ("pretrained", "final"):
        raise ValueError(
            f"embedding_type must be 'pretrained' or 'final', got {embedding_type!r}."
        )

    if df is None or len(df) == 0:
        return {}

    df = validate_repertoire_columns(df)
    df_u = aggregate_duplicate_clones(df)
    if len(df_u) == 0:
        return {}

    vgene_table = _load_vgene_table()
    needs_cdr = not {"cdr1", "cdr2", "cdr2_5"}.issubset(df_u.columns)
    if needs_cdr:
        df_u = df_u.merge(vgene_table, on="v_gene", how="left")
        n_before = len(df_u)
        df_u = df_u.dropna(subset=["cdr1", "cdr2", "cdr2_5"]).reset_index(drop=True)
        n_dropped = n_before - len(df_u)
        if n_dropped > 0:
            import warnings

            warnings.warn(
                f"Dropped {n_dropped} clone(s) whose V gene has no CDR1/CDR2/CDR2.5 "
                "entry in the reference lookup table (likely a non-TRB or "
                "unrecognized V gene)."
            )
    if len(df_u) == 0:
        return {}

    if max_unique is not None:
        df_u = df_u.head(int(max_unique)).reset_index(drop=True)
        if len(df_u) == 0:
            return {}

    dev = resolve_device(device)
    bundle = _load_models(dev)

    emb480 = _build_base_embeddings(
        df_u, bundle["base_model"], bundle["token2idx"], dev, batch_size, max_len, num_workers,
        use_amp=use_amp,
    )
    if emb480.shape[0] != len(df_u):
        raise RuntimeError(f"Unexpected embedding shape {emb480.shape} vs {len(df_u)} clones.")

    if embedding_type == "pretrained":
        final_emb = emb480.astype(np.float32, copy=False)
    else:
        Z_full_list = _encode_ensemble(bundle["proj_models"], emb480, dev, batch_size)
        final_emb = _fuse_ensemble(Z_full_list, bundle["rotations"])

    keys = list(zip(df_u["cdr3aa"].tolist(), df_u["v_gene"].tolist()))
    result: Dict[CloneKey, np.ndarray] = {keys[i]: final_emb[i] for i in range(len(keys))}

    if save_path is not None:
        with open(save_path, "wb") as f:
            pickle.dump(result, f, protocol=pickle.HIGHEST_PROTOCOL)

    return result


def attach_embeddings(
    df: pd.DataFrame,
    embeddings: Optional[Dict[CloneKey, np.ndarray]] = None,
    device: str = "auto",
    **embed_kwargs,
) -> pd.DataFrame:
    """Validate a repertoire and attach a per-clone 'embedding' column
    (numpy array per row), computing embeddings if not already provided.
    Used internally by compute_rds / plot_umap / energy_shift /
    build_reference so they all share one code path from raw df ->
    embedded, weighted clones.

    Deliberately does NOT deduplicate (cdr3aa, v_gene) rows here, even
    though embed_repertoire() dedupes internally for its own efficiency
    (one embedding per unique clone). The original row-level structure —
    including any genuine duplicate clone rows and their individual
    counts — must be preserved for downstream multinomial downsampling
    to match the original (non-packaged) scoring scripts, which never
    aggregate rows at this stage either.
    """
    df = validate_repertoire_columns(df)
    if embeddings is None:
        embeddings = embed_repertoire(df, device=device, **embed_kwargs)
    df["clone_key"] = list(zip(df["cdr3aa"], df["v_gene"]))
    df["embedding"] = df["clone_key"].map(embeddings)
    df = df.dropna(subset=["embedding"]).reset_index(drop=True)
    return df
